### PR TITLE
Copy root scripts when building

### PR DESCRIPTION
**Pull request by aldeed**
To avoid duplication of scripts, there is now a root `scripts` folder. Any scripts placed in root `scripts` are combined with image-specific `/scripts` just before the `docker build` command runs.

The full Docker build context is copied into a root `build` folder, which is ignored by Git. The `docker build` happens there.

`fix-volumes.sh` is moved to use this pattern. Currently `entrypoint.sh` is a bit different for each, so that will be dealt with later.

Also added some missing docs to the README.

### CODE REVIEW

**Comment by aldeed** [comment]
@focusaurus @rosshadden I didn't add any removal of the copied scripts after the build, and I didn't gitignore them because it's a bit hard to do given that some things in the context `scripts` folder can't be gitignored.

On CI it won't matter. When building locally it's a bit annoying, but not horrible unless you can think of a clever solution.

**Review by rosshadden — APPROVED** [review]

**Comment by rosshadden** [comment]
What do you mean by this?:
> some things in the context scripts folder can't be gitignored

Can't we ignore `/images/*/*/scripts` or something?

**Comment by aldeed** [comment]
@rosshadden Some scripts are unique to the single image and actually live in the image-specific folder. Root scripts are copied into there temporarily, alongside the ones that are committed there. Unless we list all root scripts specifically in the gitignore (which might be fine), there wouldn't be any other way to determine which are which.

**Review by focusaurus — CHANGES_REQUESTED** [review]
I would typically do this with a `build` or `.build` directory in the repo root which is gitignored and do all my work under that. Pretty tried-and-true pattern.

**Comment by aldeed** [comment]
@focusaurus Updated to copy everything to `/build`, which is ignored by Git.

**Review by focusaurus — APPROVED** [review]
:+1:

**Pull request merged**
