### PR TITLE
add git to node-dev

### PR DESCRIPTION
**Pull request by misha-erm**
Git is not installed in node-dev image so it's not possible to use git repos as packages

### CODE REVIEW

**Comment by misha-erm** [comment]
Hello, 
Can we merge this, please? @aldeed @rosshadden

**Comment by rosshadden** [comment]
@MikeYermolayev If your needs are such that you need `git` in the image so you can use it with npm, I think your best course of action is to extend the image and add `git` to your own. A case for `git` could certainly be made based around it being generally helpful in a dev environment, but with your specific use case it just doesn't make sense to add to the image. You would run into the same problem with the node-prod image when you go to use it for production, and in that case the "generally helpful in a dev environment" argument loses its ground.

**Comment by misha-erm** [comment]
@rosshadden thanks for the reply. 
My first idea was to do it locally specifically for my use case but the reason why I created this PR is that the git is present in node-prod image https://github.com/reactioncommerce/docker-base/blob/trunk/images/node-prod/12.14.1-v2/Dockerfile#L4

And, as you can see v2 was created for prod but not for the dev environment. And as you can see the documentation claims that git repos should be OK 
image

Looks like there is some inconsistency
Thanks

**Comment by rosshadden** [comment]
Well why didn't you say so? That's a great point, thanks!

**Comment by misha-erm** [comment]
sorry for the unclear description) 
thanks

**Pull request merged**
