### PR TITLE
Add Meteor 2.0.0-v1 image

### PR DESCRIPTION
**Pull request by loan-laux**
Signed-off-by: Loan Laux <loan@outgrow.io>

### CODE REVIEW

**Review by focusaurus — APPROVED** [review]
Looks good. Thanks! We'll have to review the upgrade path and see if there are breaking changes if we try to adopt meteor 2.

**Comment by loan-laux** [comment]
Thanks @focusaurus! As far as the update to Meteor 2.0 goes, there's no breaking change announced and it seems completely plug-n-play with a `meteor update` (see my PRs on `reaction-admin` and `reaction-identity`).

**Comment by loan-laux** [comment]
@focusaurus Are we waiting on something in particular to merge this? Anything I can help with?

**Comment by Akarshit** [comment]
@loan-laux Thanks for this. 🥇

**Pull request merged**
