### PR TITLE
refactor: DRY up all push and build scripts

### PR DESCRIPTION
**Pull request by focusaurus**

### CODE REVIEW

**Review by rosshadden — APPROVED** [review]

**Review by aldeed — CHANGES_REQUESTED** [review]
I like the optimization in general for CI but I was using the build script locally to test before pushing, too. It's nice to be sure I'm testing with the same command that CI will use. Maybe `build` could take a second arg with a partial path or some way to match on which image I want to build locally without having to build all?

**Comment by focusaurus** [comment]
Sure that's easy enough to add. Will do.

**Comment by focusaurus** [comment]
OK now you give `dockerfiles.sh` a subcommand either `build` or `push` then an optional list of paths to dockerfiles. If you omit the path list it finds them all by naming convention in the repo.

**Comment by aldeed** [comment]
@focusaurus I tried:

```sh
./dockerfiles.sh build ./images/node-dev/10.16.3-v2/Dockerfile
```

And it worked except at the end it tagged incorrectly:

```sh
Successfully tagged reactioncommerce/images:node-dev
```

I think bumping the piece nums for `name` and `tag` vars would be the solution, but I wanted to check with you in case I'm doing the command differently from what you expected.

**Comment by focusaurus** [comment]
Ah crap it's breaking depending on whether args have leading "./" or not.
Fixing...

**Comment by focusaurus** [comment]
OK switched it to grab directory path elements from the end backward which should be more robust against optional leading `./` prefix.

**Review by aldeed — APPROVED** [review]

**Comment by aldeed** [comment]
That makes sense. I verified it works now with and without prefix, and with multiple paths with a combination of prefix and not. 👍

**Pull request merged**
